Allow passing HW14 if you didn't do HW12 or HW13

diff --git a/hw14/test-part b/hw14/test-part
--- a/hw14/test-part
+++ b/hw14/test-part
@@ -30,10 +30,14 @@ cmp() {
 
 test_ok() {
     PROG="$1"
-    OUT="$1.expected"
+    BASE="$1.expected"
 
     printf "%s : " $(basename "$PROG")
-    cmp "-s" "$PROG" "$OUT" && cmp "-s -O3" "$PROG" "$OUT.opt" && echo "pass"
+    if ! cmp "-s" "$PROG" "$BASE"; then return 1; fi
+    if cmp "-s -O3" "$PROG" "$BASE.opt" > "$HERE"/o3.diff; then echo "pass"; return 0; fi
+    if cmp "-s -O3" "$PROG" "$BASE.opt3only"; then echo "pass without -O1/-O2"; return 0; fi
+    cat "$HERE"/o3.diff >&2
+    return 1
 }
 
 regen() {
@@ -60,6 +64,16 @@ regen() {
         return 1
     fi
     sed "\$d" "$HERE"/out.txt > "$OUT".opt
+    make --silent --no-print-directory -C "$DIR" run FLAGS="-s -O4" TEST="$PROG" > "$HERE"/out.txt
+    if ! grep -c "Compilation succeeded" "$HERE"/out.txt >/dev/null ||
+       grep -c "Compilation failed" "$HERE"/out.txt >/dev/null; then
+        echo "fail: file should have assembled"
+        echo "======= Output ======="
+        cat "$HERE"/out.txt
+        echo "======================"
+        return 1
+    fi
+    sed "\$d" "$HERE"/out.txt > "$OUT".opt3only
 }
 
 case $PART in
